name: EZContact e2e Test

on:
  # Manual Button Click from Github UI
  workflow_dispatch:
  # Pushing commit to the master branch
  # push:
    # branches: master
  schedule:
    # Runs tests every day at 1am
    - cron: '0 1 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: e2e Test on Chrome 
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          spec: |
             cypress/e2e/*.cy.js
             cypress/e2e/ProductCatalogs/*.cy.js
             cypress/e2e/ProductDetailPages/*.cy.js
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          # Format:
          #   * smtp://user:password@server:port
          #   * smtp+starttls://user:password@server:port
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection uses TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Daily Test Run Report
          # Required recipients' addresses:
          to: mysms33@gmail.com,yoely211@gmail.com,qatester9462@gmail.com,qatester4369@gmail.com
          # Required sender full name (address can be skipped):
          from: Alpha Automation ${{github.run_id}} # <user@example.com>
          # Optional plain body:
          body: |
            EZContact Daily Test Run Report completed successfully!
            Report Unique identifier ${{github.run_id}}
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          # ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          attachments: /home/runner/work/EZContact/EZContact/cypress/reports/html/*.html
          # Optional priority: 'high', 'normal' (default) or 'low'
          # priority: low
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 7
